name: parkspot
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.3
  flutter_bloc: ^8.0.1
  flutter_phoenix: ^1.0.0
  animation_wrappers: ^3.0.0
  google_mobile_ads: ^1.1.0
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  # http: ^0.12.0+2
  google_sign_in: ^5.2.0
  provider: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.9.0"

flutter_launcher_name:
  name: "Parkspot"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/appIcon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/address/
    - assets/footerIcons/
    - assets/icons/
    - assets/menuIcons/
    - assets/oncard/
    - assets/paymentOptions/
    - assets/Vehicle/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-Thin.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
flutter_intl:
  enabled: true